[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[patch.crates-io]
termion = { git = "https://gitlab.redox-os.org/Jezza/termion.git", branch = "windows-support" }

[dependencies]
log = "0.4.22"
